import { defineConfig } from 'vitepress'

export default defineConfig({
  title: '{{TITLE}}',
  description: 'Generated by insightify',
  themeConfig: {
    nav: {{NAV}},
    sidebar: {{SIDEBAR}},
    footer: {
      message: 'Generated by insightify'
    }
  }
})
